/* Database schema to keep the structure of entire database. */
/*Part 1 */
CREATE TABLE animals(
   id              INT PRIMARY  KEY     NOT NULL,
   name            CHAR(50)    NOT NULL,
   date_of_birth   DATE     NOT NULL,
   escape_attempts INT,
   neutered        BOOLEAN,
   weight_kg       DECIMAL
);

/*Part 2 */
ALTER TABLE animals
ADD COLUMN species CHAR(50);

/*Part 3 */
CREATE TABLE owners (
   id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   full_name       CHAR(100)    NOT NULL,
   age             INT
);

/*---*/
CREATE TABLE species (
   id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name            CHAR(100)    NOT NULL
);

ALTER TABLE animals
DROP COLUMN species;

/*---*/
ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
   ADD FOREIGN KEY (species_id) REFERENCES species (id);

/*---*/
ALTER TABLE animals
ADD COLUMN owner_id INT;

ALTER TABLE animals
   ADD FOREIGN KEY (owner_id) REFERENCES owners (id);
